server:
  tomcat:
    port-header: HEAD,PUT,DELETE,OPTIONS,TRACE,COPY,SEARCH,PROPFIND
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  #数据源
  datasource:
    url: jdbc:sqlserver://2.69.254.26:1433;DatabaseName=zhtc_project
    username: sa
    password: jsdc@2022
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    platform: sqlserver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化时建立物理连接的个数
    initial-size: 5
    # 最大连接池数量
    max-active: 20
    # 最小连接池数量
    min-idle: 5
    # 获取连接时最大等待时间
    max-wait: 60000
    # 是否缓存preparedStatement，也就是PSCache。
    pool-prepared-statements: false
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    max-pool-prepared-statement-per-connection-size: -1
    # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。
    validation-query: SELECT 1 FROM DUAL
    # 单位：秒，检测连接是否有效的超时时间。
    validation-query-timeout: 1
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    test-on-borrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    test-on-return: false
    # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    test-while-idle: true
    # 有两个含义：1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    time-between-eviction-runs-millis: 6000
    # 连接保持空闲而不被驱逐的最小时间
    min-evictable-idle-time-millis: 1800000
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
    # 配置监控服务器
    stat-view-servlet:
      login-username: admin
      login-password: rjgs@2016
      reset-enable: false
      url-pattern: /druid/*

  tomcat:
    test-while-idle: true

  #redis配置
  redis:
    database: 2
    host: 2.69.254.25
    password:
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
    timeout: 10000

  jpa:
    #打印sql
    show-sql: true
    hibernate:
      naming:
        #表的命名策略
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #自动建表
      ddl-auto: update

mybatis-plus:
  #  type-aliases-package: com.jsdc.zhtc.model
  #  mapper-locations: com/jsdc/zhly/mapper/xml/*.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略
    field-strategy: 1
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mybatis:
    configuration:
      map-underscore-to-camel-case: false

logging:
  # 保存日志文件目录路径
  file: C:/logs/log.log
#  file: C:/logs/poslog.log
  # 日志级别
#  level:
#    # 配置spring web日志级别
#    org.springframework.web: ERROR

jsdc:
  tokenExpireTime: 5
  h5StreamServerUrl : http://localhost:9988/
  streamLoginName : admin
  streamLoginPwd : 827ccb0eea8a706c4c34a16891f84e7b
  filePath: C:/file/
  loadPicPath: http://127.0.0.1:8080/fileManage/getImgView.do?id=
  loadPicPath2: https://zhtc.aldwxa.top/file/
  fileUrl: C:/posapk/
  #车牌识别服务url
  uploadUrl: http://2.69.254.19:8866/getCarnoByImage
  #车牌识别上传图片旋转90度后生成文件路径

  gateUrl:
    bs:
      open: https://zhtc.aldwxa.top/api/parkingplat/openGate.do
      close: https://zhtc.aldwxa.top/api/parkingplat/closeGate.do
    dc:
      open: https://zhtc.aldwxa.top/api/dc/openGate.do
      close: https://zhtc.aldwxa.top/api/dc/closeGate.do
      voice: https://zhtc.aldwxa.top/api/dc/voice.do
      startRtmp: https://zhtc.aldwxa.top/api/dc/startRtmp.do
      stopRtmp: https://zhtc.aldwxa.top/api/dc/stopRtmp.do
  #停车场闸机车辆图片url
  parkImageUrl : http://211.103.125.189:9055
  #停车场双通道闸机误拍时间差
  misstakeTime: 121
  gatePageUrl: https://zhtc.aldwxa.top
  #交控地址
  trafficUrl: http://221.225.83.17:7004
  trafficKey: EF941B9FD8FDE52393082D31A55BBBD1
  trafficSecret: 6EAA52C1F7A296EBCD1151FD067F3A59

#极光推送
jpush:
  app_key: 8f02a4fa717a6235734d92de
  master_secret: cf6de29f9e66432ba4ac1c32
excel-export-path: C:/excel/

#支付地址
paymentOrder:
  url: http://192.168.0.194:9052
  al-notify: https://zhtc.aldwxa.top/api

heartBeat:
  period: 60
  timeout_period_times: 10

file_review_url:
  https://zhtc.aldwxa.top/

program_url:
  https://zhtc.aldwxa.top/file/

program_path: E:/upload

qrcode_url: https://zhtc.aldwxa.top

mqtt:
  subTopic: "/a1BkUFnh0eA/108e6e026d0e2a63/user/update"
  pubTopic: "/a1BkUFnh0eA/108e6e026d0e2a63/user/set"
  broker: "tcp://58.218.188.178:1883"
  subClientId: "sub_client"
  pubClientId: "pub_client"
  max_reconnect_time: 30
